### PR TITLE
Parallel resolve and parallel retrieve

### PR DESCRIPTION
**Pull request by andreaTP**
Ref https://github.com/sbt/librarymanagement/pull/90

As proposed by @eed3si9n this PR contains a parallel implementation of Ivy `ResolveEngine` (straight from LM) and `RetrieveEngine`.

I'm unsure how to properly benchmark it... it seems a little faster ...
but these tests: https://github.com/andreaTP/sbt-launcher-bench
are dominated by network fluctuations at best of my understanding.

### CODE REVIEW

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by eed3si9n** [comment]
I'll post this here too - https://gist.github.com/eed3si9n/9d57f84170055c6661b7f3c560a5b0f0

here's how I would summarize it:
parallel
median 0m49.634s, worst 1m38.404s
parallel-parallel
median 0m47.792s, worst 1m39.897s
fixed
median 0m51.011s, worst 2m0.706s
default
median 0m51.978s, worst 2m59.811s

The median doesn't change but the worst case halves.

**Comment by andreaTP** [comment]
You would wanna change the EC to the cached one if you bet it's the best one

**Comment by eed3si9n** [comment]
Is this the best worst case?

```
// ExecutionContext.fromExecutor(Executors.newCachedThreadPool())
```

**Comment by eed3si9n** [comment]
I think parallel and parallel-parallel are within the range of error for sample size of 3.

**Comment by andreaTP** [comment]
Parallel-parallel is with the cached thread pool

**Comment by eed3si9n** [comment]
Yea. Let's use that one.

**Comment by andreaTP** [comment]
Btw just to let you know this little improvement (clearly isn't substantial) but with a VPN from Lisbon to Finland makes a minute of difference out of 4

**Comment by eed3si9n** [comment]
Yes, this would benefit ppl who have high latency to handshake Maven Central more.

**Comment by andreaTP** [comment]
Correct but the main problem is still to solve :-S

**Pull request merged**
